### ISSUE TITLE
SD card manager hanging

### ISSUE THREAD

**Issue by 111OCT111** [repetier/Repetier-Host-Mac#31] opened 2013-02-08 16:48 UTC
Sd card menu > able to see, create, delete folders. 

Upon upload of "current gcode", beachballs and stalled progress bar, to the point where it is impossible to copy or read the log output.

I was able to upload only one file,  20-mmbox.stl, gcode generated by slic3r (the packaged one from repetier host). 

More complex stl files are consistently stalling repetier host, up to a total hault.

No errors in the log ACK output. It either hangs the whole repetier app (with any slt larger than the 20-mmbox) , or saves a corrupt file (the aforementioned 20mmbox) as described bellow.

On:
Ramps 1.4 + sdRamps 
Mac os x 10.8.2 Mountain Lion
Repetier Host version 0.52 (49) + integrated Slic3r
Repetier Firmware 0.81 master branch + force repetier protocol + 250000 baud rate
Firmware compiled and uploaded using a fresh download of arduino ide 1.0.3, WITHOUT replacing the original HardwareSerial.h with the one provided in the "boards" folder. 

-Issue repeatable with 63 or 127 "receive cache" sizes, 
card reformated on different computers, 3 different sd cards, different baud rates, different file and folders names and name char lengths (from to up to 8 characters long).

Printer is working fine and printing without errors otherwise.  

Upon unmounting the SDcard, removing from sdramps and putting on usb card reader on another computer:
-Folders created  from "sd card" menu in repetier are there
-File generated from the "sdcard" -> "Upload" -> "Upload Current Gcode" is present
-The contents of the generated file (opened and copied the file contents in a simple text editor) as follows:

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

**Comment by repetier** [comment] 2013-02-08 17:24
Files uploaded with the sd card manager are in binary format. Opening them with text editor is not very usefull.

I have the same setup here and will check if I can reproduce the problem.

**Comment by 111OCT111** [comment] 2013-02-08 18:00
ok, this is the hexdump (using hexdump -C /Volumes/TEST/Y/testa  | more) of the binary files:
00000000  80 00 80 01 80 00 80 01  80 00 80 01 80 00 80 01  |................|
*
00001ed0
Ive uploaded the folder , as generated from the "sd card" menu, untouched and zipped for you to look at:
http://www.pinatastudio.com/labs/Y.zip

**Comment by repetier** [comment] 2013-02-08 18:07
Ok, checked your data and it is indeed not very usefull. All empty commands. So somewhere the data must got lost. Hope I can reproduce this. That is the next point in my todo when I solved my current problem.

**Comment by 111OCT111** [comment] 2013-02-08 18:18
right, if you •can't• reproduce it, and feel like doing a more thorough investigation, please let me know the steps necessary to help. 
Thank you.

**Comment by repetier** [comment] 2013-02-08 18:27
Looks like I can reproduce the problem. Only empty commands in my log like your binary showed. Now I only have to find the reason :-(

**Comment by repetier** [comment] 2013-02-09 15:53
Fixed in 0.53.

**Closed as completed by repetier** 2013-02-09 15:53 UTC
Labels: Bug, Fixed

**Comment by 111OCT111** [comment] 2013-02-09 16:15
great, as usual. testing and will report back. 
Thanks and have a good one!

**Comment by 111OCT111** [comment] 2013-02-09 20:31
Works flawlessly, finished a 2 hour long print no issues.
